# Generated by Django 6.1 on 2026-08-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
                ('dificuldade', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('codigo', models.TextField(blank=True)),
                ('linguagem', models.CharField(blank=True, max_length=20)),
                ('alternativas', models.JSONField()),
                ('correta', models.IntegerField()),
                ('explicacao', models.TextField()),
            ],
        ),
    ]
