# Generated by Django 6.1 on 2026-08-31 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baralho', models.CharField(max_length=20)),
                ('cartas', models.JSONField()),
                ('indice', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('sequencia', models.IntegerField(default=0)),
                ('melhor_sequencia', models.IntegerField(default=0)),
                ('descarte_usado', models.BooleanField(default=False)),
                ('descarte_na_carta', models.IntegerField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('carta_entregue_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='dificuldade',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.IntegerField()),
                ('certa', models.BooleanField()),
                ('segundos', models.IntegerField()),
                ('pontos', models.IntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='jogo.partida')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.pergunta')),
            ],
        ),
    ]
